name: deploy vps

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build docker image có truyền DATABASE_URL vào build-time
      - name: Build docker image
        run: |
          docker build --platform linux/amd64 \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -t hoangleuleu/swp-2025:v0 .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        run: docker push hoangleuleu/swp-2025:v0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            mkdir -p /home/hoang/deploy

            echo "${{ secrets.ENV_PROD }}" > /home/hoang/deploy/.env

            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

            docker pull hoangleuleu/swp-2025:v0

            docker rm -f dev_nest_graphql || true

            docker container run -dp 8080:3001 --name dev_nest_graphql \
              --network graphql_network \
              --env-file /home/hoang/deploy/.env \
              hoangleuleu/swp-2025:v0

            docker network inspect graphql_network || docker network create graphql_network
            docker network connect graphql_network dev_nest_graphql || true

            docker image prune -f
